### ISSUE TITLE
Cannot Rebuild Course

### ISSUE THREAD

**Issue by mysticbt** [RunestoneInteractive/RunestoneServer#1114]
Trying to rebuild for the next class. Fails with the error:

Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/scheduler.py", line 501, in executor
    result = dumps(_function(*args, **vars))
  File "applications/runestone/models/scheduler.py", line 49, in run_sphinx
    makePavement(http_host, rvars, sourcedir, base_course)
  File "applications/runestone/models/scheduler.py", line 138, in makePavement
    paver_stuff = paver_stuff % opts
KeyError: 'enable_chatcodes'

**Comment by bnmnetp** [comment]
Thanks for the report.   You should be good to go now.
