### ISSUE TITLE
Course building break - no .../custom_courses/.../index.rst

### ISSUE THREAD

**Issue by Mightyjo** [RunestoneInteractive/RunestoneServer#1115]
Thanks for the email yesterday evening regarding the course building borks.
I broke your course build again - or at least tried to build while you were working.  Traceback follows:

```
Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/scheduler.py", line 501, in executor
    result = dumps(_function(*args, **vars))
  File "applications/runestone/models/scheduler.py", line 60, in run_sphinx
    shutil.copy(path.join(custom_dir, 'index.rst'), path.join(sourcedir, '_sources', 'index.rst'))
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/bmiller/Runestone/web2py/applications/runestone/custom_courses/phdprogramming/index.rst'
```

**Comment by bnmnetp** [comment]
sorry that was a by product of the original fail.  I've manually copied over your index.rst file.

**Comment by Mightyjo** [comment]
Thanks! All good now.
