### ISSUE TITLE
Creating a course failed Jan 11 2019

### ISSUE THREAD

**Issue by cigas** [RunestoneInteractive/RunestoneServer#1188]
Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/scheduler.py", line 501, in executor
    result = dumps(_function(*args, **vars))
  File "applications/runestone/models/scheduler.py", line 49, in run_sphinx
    makePavement(http_host, rvars, sourcedir, base_course)
  File "applications/runestone/models/scheduler.py", line 142, in makePavement
    paver_stuff = paver_stuff % opts
KeyError: 'allow_pairs'

**Comment by bnmnetp** [comment]
Sorry for the problem.  Its fixed.

**Comment by cigas** [comment]
Thanks.
