### ISSUE TITLE
I can not create course, please help

### ISSUE THREAD

**Issue by elifsudegokay** [RunestoneInteractive/RunestoneServer#1207]
I am student assistant and new in runestone. I really need help to solve this issue.
I can not create course in server. I do not know is it important but web2py  running on port:80 with nginx. 

Traceback (most recent call last):
  File "/home/gokhansahin/web2py/gluon/scheduler.py", line 501, in executor
    result = dumps(_function(*args, **vars))
  File "applications/runestone/models/scheduler.py", line 79, in run_sphinx
    paver_main(args=["build"])
  File "/home/foo/local/lib/python2.7/site-packages/paver/tasks.py", line 890, in main
    _launch_pavement(args)
  File "/home/foo/local/lib/python2.7/site-packages/paver/tasks.py", line 870, in _launch_pavement
    _process_commands(args, auto_pending=auto_pending)
  File "/home/foo/local/lib/python2.7/site-packages/paver/tasks.py", line 821, in _process_commands
    task()
  File "/home/foo/local/lib/python2.7/site-packages/paver/tasks.py", line 333, in __call__
    retval = environment._run_task(self.name, self.needs, self.func)
  File "/home/foo/local/lib/python2.7/site-packages/paver/tasks.py", line 217, in _run_task
    self._exit(1)
  File "/home/foo/local/lib/python2.7/site-packages/paver/tasks.py", line 85, in _exit
    sys.exit(1)
SystemExit: 1

**Comment by bnmnetp** [comment]
This traceback doesn’t give much help.  You didn’t include the error message either, so its hard to say what is going on.  You are following all of the instructions on the server README ?  Have you run the `rsmanage initdb` command?  Have you installed the source for the course you want in the books folder?  Can you access that course?  By default `rsmanage initdb` creates database entries for thinkcspy, fopp, and many others, but you still need to clone those repositories and build them.


If you are running your own server for a single course there is no reason to use the create course feature.

**Comment by elifsudegokay** [comment]
Thank you for your answer. Yes i followed instructions again and again but I could not find anything I missed. I can not access the course and we have more than one course.  Now, I run 

(foo) root@runestone:/home/gokhansahin/web2py/applications/runestone/books# rsmanage initdb --reset
Resetting the database will delete the database and the contents of the databases folder.  Are you sure? [y/N]: y
SELECT pg_catalog.set_config('search_path', '', false)
CREATE DATABASE runestone;
Removing all files in databases/
Initializing the database
Running: python web2py.py --no-banner -S runestone -M -R applications/runestone/rsmanage/initialize_tables.py 
/home/foo/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Definining initial Courses
Adding Constraints and Indices


After reset, when I try to create course again but it was more than 10 minute.


![screen shot 2019-02-09 at 18 19 21](https://user-images.githubusercontent.com/28874640/52522501-34db9380-2c97-11e9-807e-1841ff1d1738.png)

..................

This is error message 

(foo) root@runestone:/home/gokhansahin/web2py# ./start
Be sure to activate your virtual environment
/home/foo/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
web2py Web Framework
Created by Massimo Di Pierro, Copyright 2007-2019
Version 2.17.2-stable+timestamp.2018.10.06.18.54.02
Database drivers available: sqlite3, psycopg2, pymysql, imaplib
no password, no admin interface
starting scheduler for "runestone"...

please visit:
	http://127.0.0.1:8000/
use "kill -SIGTERM 1833" to shutdown the web2py server

Currently running 1 scheduler processes

Processes started
starting scheduler
(foo) root@runestone:/home/gokhansahin/web2py# /home/foo/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/gokhansahin/web2py/gluon/scheduler.py", line 637, in run
    self.send_heartbeat(counter)
  File "/home/gokhansahin/web2py/gluon/scheduler.py", line 1171, in send_heartbeat
    self.db._uri, folder=self.db._adapter.folder, decode_credentials=True)
  File "/home/foo/local/lib/python2.7/site-packages/pydal/base.py", line 169, in __call__
    obj = super(MetaDAL, cls).__call__(*args, **kwargs)
  File "/home/foo/local/lib/python2.7/site-packages/pydal/base.py", line 474, in __init__
    "Failure to connect, tried %d times:\n%s" % (attempts, tb)
RuntimeError: Failure to connect, tried 5 times:
Traceback (most recent call last):
  File "/home/foo/local/lib/python2.7/site-packages/pydal/base.py", line 454, in __init__
    self._adapter = adapter(**kwargs)
  File "/home/foo/local/lib/python2.7/site-packages/pydal/adapters/postgres.py", line 25, in __call__
    return AdapterMeta.__call__(cls, *args, **kwargs)
  File "/home/foo/local/lib/python2.7/site-packages/pydal/adapters/__init__.py", line 40, in __call__
    obj = super(AdapterMeta, cls).__call__(*args, **kwargs)
  File "/home/foo/local/lib/python2.7/site-packages/pydal/adapters/postgres.py", line 48, in __init__
    driver_args, adapter_args, do_connect, after_connection)
  File "/home/foo/local/lib/python2.7/site-packages/pydal/adapters/base.py", line 368, in __init__
    super(SQLAdapter, self).__init__(*args, **kwargs)
  File "/home/foo/local/lib/python2.7/site-packages/pydal/adapters/base.py", line 50, in __init__
    self._initialize_(do_connect)
  File "/home/foo/local/lib/python2.7/site-packages/pydal/adapters/postgres.py", line 56, in _initialize_
    user = self.credential_decoder(m.group('user'))
  File "/home/foo/local/lib/python2.7/site-packages/pydal/base.py", line 403, in <lambda>
    credential_decoder = lambda cred: urllib.unquote(cred)
NameError: global name 'urllib' is not defined


Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/gokhansahin/web2py/gluon/scheduler.py", line 637, in run
    self.send_heartbeat(counter)
  File "/home/gokhansahin/web2py/gluon/scheduler.py", line 1171, in send_heartbeat
    self.db._uri, folder=self.db._adapter.folder, decode_credentials=True)
  File "/home/foo/local/lib/python2.7/site-packages/pydal/base.py", line 169, in __call__
    obj = super(MetaDAL, cls).__call__(*args, **kwargs)
  File "/home/foo/local/lib/python2.7/site-packages/pydal/base.py", line 474, in __init__
    "Failure to connect, tried %d times:\n%s" % (attempts, tb)
RuntimeError: Failure to connect, tried 5 times:
Traceback (most recent call last):
  File "/home/foo/local/lib/python2.7/site-packages/pydal/base.py", line 454, in __init__
    self._adapter = adapter(**kwargs)
  File "/home/foo/local/lib/python2.7/site-packages/pydal/adapters/postgres.py", line 25, in __call__
    return AdapterMeta.__call__(cls, *args, **kwargs)
  File "/home/foo/local/lib/python2.7/site-packages/pydal/adapters/__init__.py", line 40, in __call__
    obj = super(AdapterMeta, cls).__call__(*args, **kwargs)
  File "/home/foo/local/lib/python2.7/site-packages/pydal/adapters/postgres.py", line 48, in __init__
    driver_args, adapter_args, do_connect, after_connection)
  File "/home/foo/local/lib/python2.7/site-packages/pydal/adapters/base.py", line 368, in __init__
    super(SQLAdapter, self).__init__(*args, **kwargs)
  File "/home/foo/local/lib/python2.7/site-packages/pydal/adapters/base.py", line 50, in __init__
    self._initialize_(do_connect)
  File "/home/foo/local/lib/python2.7/site-packages/pydal/adapters/postgres.py", line 56, in _initialize_
    user = self.credential_decoder(m.group('user'))
  File "/home/foo/local/lib/python2.7/site-packages/pydal/base.py", line 403, in <lambda>
    credential_decoder = lambda cred: urllib.unquote(cred)
NameError: global name 'urllib' is not defined


Thank you

**Comment by bnmnetp** [comment]
Well, the urllib not defined error reminds me of an old bug in web2py.  What version of web2py are you using?

Also what are the contents of applications/runestone/books ?  What about applications/runestone/build ?

**Comment by bnmnetp** [comment]
Hmmm, it also looks like you are using pedal from site-packages rather than from web2py distribution.  That is not a configuration I have tested, and that version of pydal may be old and contain the bug I was thinking of.

**Comment by elifsudegokay** [comment]
web2py version : Version 2.17.2-stable+timestamp.2018.10.06.18.54.02
Books are :
![screen shot 2019-02-09 at 18 38 19](https://user-images.githubusercontent.com/28874640/52522694-c9df8c00-2c99-11e9-9aa4-bd18a5f61dad.png)

We translated StudentCSP's some chapters in Turkish we are using it for 5 months.
Now we need its original version and I have change the name of original folder as ACM114.
...................

Build folder:
![screen shot 2019-02-09 at 18 38 19](https://user-images.githubusercontent.com/28874640/52522740-5722e080-2c9a-11e9-85e2-f598a21386d0.png)

These were my trials, when I clicked them in interface there was 404: Page Not Found

Should I remove pydal ? 

Thank you

**Comment by bnmnetp** [comment]
Yes, if the build is successful then those folders get cleaned up and removed.

I would start by uninstalling pydal as its better to use the version that comes with the released version of web2py.

**Comment by elifsudegokay** [comment]
it worked thank you :)
