### ISSUE TITLE
Server crash on home page load on own docker setup

### ISSUE THREAD

**Issue by donnerc** [RunestoneInteractive/RunestoneServer#1339]
**What Course are you in**
I'm running my own Docker setup

**Describe the bug**
On /index request, the server crashes with following error

**Traceback**

```
File "/srv/web2py/gluon/main.py", line 440, in wsgibase
    serve_controller(request, response, session)
  File "/srv/web2py/gluon/main.py", line 176, in serve_controller
    page = run_controller_in(request.controller, request.function, environment)
  File "/srv/web2py/gluon/compileapp.py", line 657, in run_controller_in
    restricted(ccode, environment, layer=filename)
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/srv/web2py/applications/runestone/controllers/default.py", line 646, in <module>
  File "/srv/web2py/gluon/globals.py", line 422, in <lambda>
    self._caller = lambda f: f()
  File "/srv/web2py/gluon/tools.py", line 3857, in f
    self.settings.login_url + '?_next=' + urllib_quote(next))
  File "/srv/web2py/gluon/tools.py", line 96, in call_or_redirect
    redirect(f(*args))
  File "/srv/web2py/gluon/tools.py", line 1387, in <lambda>
    on_failed_authentication=lambda x: redirect(x),
  File "/srv/web2py/gluon/http.py", line 182, in redirect
    **headers)
gluon.http.HTTP: 303 SEE OTHER

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/web2py/gluon/main.py", line 456, in wsgibase
    session._try_store_in_db(request, response)
  File "/srv/web2py/gluon/globals.py", line 1236, in _try_store_in_db
    modified_datetime=request.now.isostring(),
AttributeError: 'datetime.datetime' object has no attribute 'isostring'
```
The first exception is just a web2py redirect. The problem is in the second exception and seems to be related to a recent change in web2py : https://github.com/web2py/web2py/commit/0f638f9cdf62832b01c62c4c2bcbb8e326906392 which refers to a non existent `datetime.datetime.isostring()` method (at least on Python 3.7) but I'm not 100% sure.

**Additional context**

**Comment by bnmnetp** [comment]
I ran into this as well... It is a bug in the latest commit of web2py.

My workaround was to shell in to the docker container, download web2py_src.zip from the web2py website. and unzip it over the top of the existing web2py install from GitHub.

**Comment by donnerc** [comment]
Thanks for the quick reply. In that case, suggest changing the Docker file by replacing 

```
RUN git clone https://github.com/web2py/web2py ${WEB2PY_PATH} && \
    cd ${WEB2PY_PATH} && \
    git submodule update --init --recursive
```

by

```
RUN wget https://mdipierro.pythonanywhere.com/examples/static/web2py_src.zip && \
    unzip web2py_src.zip && \
    rm -f web2py_src.zip && \
    mv web2py ${WEB2PY_PATH} && \
    cd ${WEB2PY_PATH}
```

to avoid blindly cloning an unstable master branch of web2py and getting the officially distributed source code of web2py under the download section of their website. This is working for me.

**Comment by bnmnetp** [comment]
Thanks, you are one step ahead of me.

**Comment by bnmnetp** [comment]
done
