### ISSUE TITLE
Exception in student report dashboard

### ISSUE THREAD

**Issue by bjones1** [RunestoneInteractive/RunestoneServer#1572]
Here's a traceback from my server (somewhat dated -- perhaps this is fixed now?)

```
Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/www-data/web2py/applications/runestone/controllers/dashboard.py", line 1001, in <module>
  File "/home/www-data/web2py/gluon/globals.py", line 430, in <lambda>
    self._caller = lambda f: f()
  File "/home/www-data/web2py/gluon/tools.py", line 3867, in f
    return action(*a, **b)
  File "/home/www-data/web2py/applications/runestone/controllers/dashboard.py", line 326, in studentreport
    data_analyzer.load_assignment_metrics(sid, not for_dashboard)
  File "/home/www-data/web2py/applications/runestone/modules/db_dashboard.py", line 671, in load_assignment_metrics
    100 * this_score / assign["points"]
TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'
```

**Comment by bnmnetp** [comment]
That looks familiar, and if it is the same problem it was fixed quite a while ago.

**Comment by bjones1** [comment]
Sounds good, thanks for checking! (This is some catch-up work I'd been putting off for a while...)
