### ISSUE TITLE
Exception on enroll_student

### ISSUE THREAD

**Issue by bjones1** [RunestoneInteractive/RunestoneServer#1611]
Here's an exception I received from my server. It looks like we need to catch and report this exception -- see https://github.com/RunestoneInteractive/RunestoneServer/blob/master/controllers/admin.py#L2461.

```
Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/www-data/web2py/applications/runestone/controllers/admin.py", line 2810, in <module>
  File "/home/www-data/web2py/gluon/globals.py", line 430, in <lambda>
    self._caller = lambda f: f()
  File "/home/www-data/web2py/gluon/tools.py", line 3875, in f
    return action(*a, **b)
  File "/home/www-data/web2py/applications/runestone/controllers/admin.py", line 2462, in enroll_students
    for row in validation_reader:
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "/usr/lib/python3.8/encodings/utf_8_sig.py", line 69, in _buffer_decode
    return codecs.utf_8_decode(input, errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 15-16: invalid continuation byte
```

We also need add a test to show the problem and that it's fixed.

**Comment by bjones1** [comment]
Good point; I didn't, and I'm not sure how to track down the offending file to investigate.

**Comment by bnmnetp** [comment]
This endpoint is only called when you upload a CSV file to enroll a bunch of students in a class.  Who else would have done this?

**Comment by bjones1** [comment]
I assume another instructor can do this? Several people use the e-book I wrote.
