### ISSUE TITLE
Link to "Instructor Page" directs to "Report a Bug" page

### ISSUE THREAD

**Issue by sprenks18** [RunestoneInteractive/RunestoneServer#1756]
**What Course are you in**
I am in wlu_csci209_2021 and also tried WLU_CSCI335_S21

**What Page were you on**

https://runestone.academy/runestone/books/published/webfundamentals/index.html

**What is your username**
sprenkle

**Describe the bug**
In the user drop down menu, I click on "Instructor's Page", which sends me to https://runestone.academy/runestone/admin/index
which has the title "Report a Bug".

**Traceback**
 ---------------- Traceback --------------
    Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/main.py", line 444, in wsgibase
    serve_controller(request, response, session)
  File "/home/bmiller/Runestone/web2py/gluon/main.py", line 179, in serve_controller
    page = run_controller_in(request.controller, request.function, environment)
  File "/home/bmiller/Runestone/web2py/gluon/compileapp.py", line 657, in run_controller_in
    ccode = getcfs(layer, filename, lambda: compile2(code, filename))
  File "/home/bmiller/Runestone/web2py/gluon/cfs.py", line 50, in getcfs
    data = filter()
  File "/home/bmiller/Runestone/web2py/gluon/compileapp.py", line 657, in <lambda>
    ccode = getcfs(layer, filename, lambda: compile2(code, filename))
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 205, in compile2
    return compile(code, layer, 'exec')
  File "<fstring>", line 1
    (searchdict=)
               ^
SyntaxError: invalid syntax

**Javascript Errors**
None.

**Comment by JocelynHumphries** [comment]
I have the identical problem.

**Comment by mraharrisoncs** [comment]
I have the same problem
course williamA23 (copy of StudentCSP). User mraharrison.
Straight to Report a Bug when I click on Instructor page.

**Comment by bnmnetp** [comment]
Fixed!  Sorry for the inconvenience.  This slipped through our automated tests and my manual testing.  It is a feature that is not supported by python3.7 but is supported by python 3.8 and 3.9.

Time to get all of Runestone’s servers off of 3.7!!
