### ISSUE TITLE
Error on course build

### ISSUE THREAD

**Issue by tobydragon** [RunestoneInteractive/RunestoneServer#678]
Attempted to build new thinkcspy course, with the following ID: IC_COMP_171_SP_16_DRAGON

Received the following error:
`Traceback (most recent call last):
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/scheduler.py", line 237, in executor
    result = dumps(_function(*args, **vars))
  File "applications/runestone/models/scheduler.py", line 46, in run_sphinx
    makePavement(http_host, rvars, sourcedir)
  File "applications/runestone/models/scheduler.py", line 153, in makePavement
    paver_stuff = paver_stuff % opts
KeyError: 'basecourse'`

**Comment by bnmnetp** [comment]
Thanks Toby,

I forgot to do a pull.

Should be fine now.

Brad

**Comment by tobydragon** [comment]
Works great Thanks!
