### ISSUE TITLE
Course Building Error

### ISSUE THREAD

**Issue by CarrieLindeman** [RunestoneInteractive/RunestoneServer#731]
Tried to build a thinkcspy course with the name CarrieProjTest and I received this error.

Traceback (most recent call last):
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/scheduler.py", line 237, in executor
    result = dumps(_function(*args, **vars))
  File "applications/runestone/models/scheduler.py", line 107, in run_sphinx
    scd, ct = findChaptersSubChapters(path.join(sourcedir, '_sources', idxname))
  File "/home/bnmnetp/Environments/runestonelive/lib/python2.7/site-packages/runestone/server/chapternames.py", line 25, in findChaptersSubChapters
    ftext = open(tocfile, 'r').readlines()
IOError: [Errno 2] No such file or directory: '/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/build/CarrieProjTest/_sources/toc.rst'

**Comment by bnmnetp** [comment]
Sorry @CarrieLindeman !  We are doing a bunch of summer improvements, and I had not updated the code on the live server to sync up with the book.  I have done that now, and it should work for you.
