### ISSUE TITLE
Null Values are accepted in bug reporting form

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#757]
**Raised by:** courselib@interactivepython.org<br>
``` Traceback (most recent call last):
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/restricted.py", line 212, in restricted
    exec ccode in environment
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/controllers/default.py", line 298, in 
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/globals.py", line 194, in 
    self._caller = lambda f: f()
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/controllers/default.py", line 287, in sendreport
    body = 'Error reported in course ' + request.vars['coursename'] + ' on page ' + request.vars['pagename'] + '\n' + request.vars['bugdetails']
TypeError: cannot concatenate 'str' and 'NoneType' objects
 ```<br><br>

**Comment by bnmnetp** [comment]
@hangde01, The required attribute of an input does not do anything other than apply formatting.  Could you write a little javascript function to be called on submit  to verify that required fields are filled in?

**Comment by bnmnetp** [comment]
You may also want to use a web2py form object rather than hardcoding the form in the view.  See:  http://web2py.com/books/default/chapter/29/07/forms-and-validators#FORM

**Comment by hangde01** [comment]
There's a new pull request #795 that should solve the issue. Is changing the form from a hardcoded form to a web2py form object important? If so, I can write that up today/tomorrow.

**Comment by bnmnetp** [comment]
Closing.
