### ISSUE TITLE
Recursion Chapter crashes student progress

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#810]
**Raised by:** courselib@interactivepython.org<br>
``` Traceback (most recent call last):
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/restricted.py", line 212, in restricted
    exec ccode in environment
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/controllers/dashboard.py", line 144, in 
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/globals.py", line 194, in 
    self._caller = lambda f: f()
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/tools.py", line 3022, in f
    return action(*a, **b)
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/controllers/dashboard.py", line 37, in index
    data_analyzer.load_chapter_metrics(selected_chapter)
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/models/db_dashboard.py", line 294, in load_chapter_metrics
    self.progress_metrics.update_metrics(self.logs, self.db_chapter_progress)
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/models/db_dashboard.py", line 210, in update_metrics
    self.sub_chapters[row.user_sub_chapter_progress.sub_chapter_id].add_activity(row)
KeyError: 'CalculatingtheSumofaListofNumbers'
 ```<br><br>

**Comment by bnmnetp** [comment]
I *think* this is caused because my test student had a chapter with the chapter id of Recursion in both the thinkcspy book as well as the pythonds book.  user_sub_chapter_progress should somehow tie into the course rather than only the userid.

More investigation is required.

**Comment by bnmnetp** [comment]
That is definitely the problem.  The solution is that we really need to do some surgery on the xxx_progress tables and add the course id to this table.  This will also prevent the somewhat weird behavior of having every course with the same base course show the same progress.

**Comment by bnmnetp** [comment]
I put a bandaid on this so it won't crash.  But the underlying problem remains.
