### ISSUE TITLE
Not all act fields can be split using : -- particuarly submission logs from a timed exam

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#844]
```
Traceback (most recent call last):
File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/restricted.py", line 212, in restricted
exec ccode in environment
File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/controllers/dashboard.py", line 149, in <module>
File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/globals.py", line 194, in <lambda>
self._caller = lambda f: f()
File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/tools.py", line 3022, in f
return action(*a, **b)
File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/controllers/dashboard.py", line 41, in index
data_analyzer.load_chapter_metrics(selected_chapter)
File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/models/db_dashboard.py", line 303, in load_chapter_metrics
self.problem_metrics.update_metrics(self.logs)
File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/models/db_dashboard.py", line 121, in update_metrics
self.problems[row.div_id].add_data_point(row)
File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/models/db_dashboard.py", line 46, in add_data_point
choice = answer[1]
IndexError: list index out of range
```

**Comment by bnmnetp** [comment]
fixed
