### ISSUE TITLE
crash in models/grouped_assignments

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#871]
```
Traceback (most recent call last):
File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/restricted.py", line 212, in restricted
exec ccode in environment
File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/views/assignments/index.html", line 125, in <module>
File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/models/grouped_assignments.py", line 104, in points
return sum([t.points(projected, potential) for t in self.assignment_type_grades])
File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/models/grouped_assignments.py", line 86, in points
return sum(vals[self.assignments_dropped:])
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

@presnick maybe some incompatibility creeping in??

**Comment by presnick** [comment]
Looking at lines 18-32, in grouped_assignments.py, I think there are two
possibilities:
-- there is an assignment that doesn't specify a number of points (line 23)
-- there is a released assignment where, for some student, the score is
null rather than 0 (line 25)

Is this just from the log files, or is it an error that you got and can
repeat?

**Comment by bnmnetp** [comment]
@presnick Every time a controller crashes and generates a traceback, I get an email with the traceback.  So, in this case it is not happening to me, but rather to some other teacher out there somewhere...

Looking in the database, I see that there are 88 assignments where the points value is null.  There are no rows in the grades table where the score is null.

I could update the assignments table to have the points be 0 rather than null.

**Comment by presnick** [comment]
Probably easier to update line 23 of grouped_assignments.py to return 0
when self.assignment_score is None.
