### ISSUE TITLE
Need to escape ' in sids for usernames with 's in them

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#894]
```
Traceback (most recent call last):
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/restricted.py", line 212, in restricted
    exec ccode in environment
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/controllers/ajax.py", line 957, in <module>
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/globals.py", line 194, in <lambda>
    self._caller = lambda f: f()
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/controllers/ajax.py", line 923, in getAssessResults
    rows = db.executesql(query)
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/dal.py", line 8001, in executesql
    adapter.execute(query)
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/dal.py", line 1784, in execute
    return self.log_execute(*a, **b)
  File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/dal.py", line 1778, in log_execute
    ret = self.cursor.execute(command, *a[1:], **b)
ProgrammingError: syntax error at or near "souza"
LINE 1: ...mp_2' and course_name='pythonds' and sid='RachelD'souza' ord...
```

**Comment by gardhi01** [comment]
Tyler and I were looking at this, and neither of us could create a username with a single quote.  Is there something else we're missing?

**Comment by bnmnetp** [comment]
Its not necessarily a username, it may just be a last name such as O'Connor, however in the example I gave I suspect that person registered using their Google id.
