### ISSUE TITLE
Following README Instructions doesn't create tables

### ISSUE THREAD

**Issue by MarkEstefanos** [RunestoneInteractive/RunestoneServer#904]
After running web2py, when I go to run `runestone build` I get the following error:

```
(runestone) ubuntu@alf-summer-prep:~/workspace/python-server/web2py/applications/runestone$ runestone build
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/runestone/bin/runestone", line 7, in <module>
    from runestone.__main__ import main
  File "/home/ubuntu/.virtualenvs/runestone/local/lib/python2.7/site-packages/runestone/__init__.py", line 1, in <module>
    from .activecode import *
  File "/home/ubuntu/.virtualenvs/runestone/local/lib/python2.7/site-packages/runestone/activecode/__init__.py", line 1, in <module>
    from .activecode import *
  File "/home/ubuntu/.virtualenvs/runestone/local/lib/python2.7/site-packages/runestone/activecode/activecode.py", line 26, in <module>
    from runestone.server.componentdb import addQuestionToDB, addHTMLToDB
  File "/home/ubuntu/.virtualenvs/runestone/local/lib/python2.7/site-packages/runestone/server/componentdb.py", line 30, in <module>
    questions = Table('questions', meta, autoload=True, autoload_with=engine)
  File "/home/ubuntu/.virtualenvs/runestone/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 440, in __new__
    metadata._remove_table(name, schema)
  File "/home/ubuntu/.virtualenvs/runestone/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/ubuntu/.virtualenvs/runestone/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 435, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/ubuntu/.virtualenvs/runestone/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 510, in _init
    self._autoload(metadata, autoload_with, include_columns)
  File "/home/ubuntu/.virtualenvs/runestone/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 522, in _autoload
    self, include_columns, exclude_columns
  File "/home/ubuntu/.virtualenvs/runestone/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1972, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/runestone/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1477, in run_callable
    return callable_(self, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/runestone/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 364, in reflecttable
    return insp.reflecttable(table, include_columns, exclude_columns)
  File "/home/ubuntu/.virtualenvs/runestone/local/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 563, in reflecttable
    table_name, schema, **table.dialect_kwargs):
  File "/home/ubuntu/.virtualenvs/runestone/local/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 369, in get_columns
    **kw)
  File "<string>", line 2, in get_columns
  File "/home/ubuntu/.virtualenvs/runestone/local/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 54, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/ubuntu/.virtualenvs/runestone/local/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2377, in get_columns
    info_cache=kw.get('info_cache'))
  File "<string>", line 2, in get_table_oid
  File "/home/ubuntu/.virtualenvs/runestone/local/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 54, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/ubuntu/.virtualenvs/runestone/local/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2275, in get_table_oid
    raise exc.NoSuchTableError(table_name)
sqlalchemy.exc.NoSuchTableError: questions
```

When I check out the psql database it also has no tables.

I'd really appreciate a hint here, as I've been stumped for a few days now. Thanks!

**Comment by bnmnetp** [comment]
Once you start web2py you need to access http://localhost:8000/runestone at least once to get the application to load and build the tables.   I see that is not listed as an explicit step in the README, so I'm guessing you didn't do that??

**Comment by MarkEstefanos** [comment]
I ended up trying that when fumbling around, and I get an internal error:
<img width="1440" alt="screen shot 2017-05-20 at 1 34 21 pm" src="https://cloud.githubusercontent.com/assets/7613936/26279171/221f3548-3d61-11e7-87c0-5a300585c102.png">

When I click the ticket link I get:
<img width="1440" alt="screen shot 2017-05-20 at 1 34 24 pm" src="https://cloud.githubusercontent.com/assets/7613936/26279174/2d3f4a08-3d61-11e7-9d18-82577e00b639.png">

Is there a way to get more debug info?

**Comment by bnmnetp** [comment]
Hmm, thats not very helpful is it.  Usually the web2py ticket links give you all kinds of traceback information.

You can check the errors folder under runestone and there should be one file for every ticket you've generated.  they are not very human readable but you can check to see if it contains more than an A.  If it does upload it here and I'll take a look.

**Comment by MarkEstefanos** [comment]
Ah, the error messages were the hint I needed. They indicated that I had an incorrect indent in my 0.py, and that was breaking everything. Thank you!

**Comment by bnmnetp** [comment]
Yes, 0.py will be one of the first things loaded.  So not much will work if thats broken.  Glad you were able to fix it.

I've updated the README so I'm going to close this.
