### ISSUE TITLE
Unsupported Operand Types for + 

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneServer#910]
```
Traceback (most recent call last): 
File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/restricted.py", line 227, in restricted 
exec ccode in environment 
File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/controllers/designer.py", line 184, in <module> 
File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/gluon/globals.py", line 417, in <lambda> 
self._caller = lambda f: f() 
File "/home/bnmnetp/webapps/uwsgi_runestone/web2py/applications/runestone/controllers/designer.py", line 51, in build 
if path.exists(path.join(request.folder,'books',request.vars.coursetype+"_A")): 
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str' 
```

**Comment by bnmnetp** [comment]
This one is a bit curious...  I'm not actually sure how this could happen -- coursetype should never be null, and folder corresponds to the course name (I think) which is a required field too...

Maybe you can try to reproduce this with various combinations of data entry on the create a course page and see whats up..

**Comment by conzty01** [comment]
I am not sure how this happened either-- especially since the thinkcspy book is selected by default.  Do you know if this is an isolated instance or does it happen often?  Everything seems to be fine in the designer.py script and even adding a few print statements to show the request.vars shows that coursetype is present in each of my tests.  The only thing I can think is that somehow the radio was not selected by default when the page loaded and the user just tried to click through quickly.  Even in that instance, the radio should just not be passed in the HTTP request to the request.vars dictionary.
