### ISSUE TITLE
"Student progress page is not available for thinkcspy"

### ISSUE THREAD

**Issue by MarkEstefanos** [RunestoneInteractive/RunestoneServer#964]
Hi! Sorry to keep pestering, but it's important that I'm able to see how far students are in the book. I tried pulling the latest runestone server, and I get this message when I try and view student progress:
<img width="675" alt="screen shot 2017-07-13 at 12 35 15 pm" src="https://user-images.githubusercontent.com/7613936/28184337-de5029bc-67c7-11e7-97e3-3799deca3efa.png">

Any ideas for troubleshooting steps? Thanks!

**Comment by bnmnetp** [comment]
Mark,

If you are running the latest from github then look in controllers/dashboard.py about line 29

```
    if auth.user.course_name in ['thinkcspy','pythonds','JavaReview','JavaReview-RU', 'StudentCSP']:
        session.flash = "Student Progress page not available for {}".format(auth.user.course_name)
        return redirect(URL('admin','admin'))
```

Take thinkcspy out of that list.    The server is really evolved in the direction of supporting http://interactivepython.org more than one individual running their own server.  The volume on that site for the thinkcspy course kills the task to generate that report. 

I'm sorry that you jumped into the middle of our development cycle, but you really are one of a small number of people (as far as I know) that are running their own server rather than creating a course on ours.

Naturally, I'm curious why you decided to run your own.

Brad

**Comment by bnmnetp** [comment]
Of course, if all else fails, since you are running your own server, you can always query the database to see your students progress :smile:

**Comment by MarkEstefanos** [comment]
There's no need to apologize! It's totally reasonable to cater the site to your needs, and I immensely appreciate the help. 

As to why we decided to run our own, it was essentially for cosmetic reasons. The incoming students at Minerva learn basic programming in the summer before their freshman year, making this textbook one of their first impressions of the university. I ended up making small UX tweaks like making the left and right page buttons larger, making the login page simpler, and adding annotation features via Hypothesis. For next year I'll recommend that they stick to your server to prevent a few headaches. 😄 

After removing that line I get this error:
`<type 'exceptions.AttributeError'> 'DashboardDataAnalyzer' object has no attribute 'problem_metrics'"` 
In case I can't get this working, I'm assuming DashboardDataAnalyzer has the queries I need?

**Comment by bnmnetp** [comment]
Well.... I just made myself an instructor for thinkcspy on my dev machine and took it out of the list.  I'm not able to reproduce your error. I get to the progress page no problem.  Its hard to see How/why that would happen unless something else is failing that I haven't seen.

on line 43 we create a data_analyzer and in the `__init__` method initialize a problem_metrics attribute.  four lines later we access that attribute and get an error... Strange.

Things to check, that you've probably done:

* Make sure your username is an instructor should be your userid + group_id 2 in the auth_membership table.
* Make sure your username and thinkcspy course id are paired in the course_instructor table.

* If that is all good, then I'd like to see more of the traceback.

PS - larger next/previous buttons are a common request, if you've done the work a PR would be great.

Also:  RunestoneInteractive/RunestoneComponents#391 Hypothesis  or annotatorjs  -- The fact that you have Hypothesis working is very interesting to me.

**Comment by MarkEstefanos** [comment]
Sorry for the delay on this, this ended up on the backburner at work. 

Looks like my user_id is 11 (from auth_users): 
<img width="202" alt="screen shot 2017-07-28 at 11 32 59 am" src="https://user-images.githubusercontent.com/7613936/28731393-8d3371ca-7388-11e7-9872-a5711d153485.png">

My group_id is 2:
<img width="278" alt="screen shot 2017-07-28 at 11 31 35 am" src="https://user-images.githubusercontent.com/7613936/28731405-a0609c5a-7388-11e7-8123-c41de3416299.png">

Thinkcspy is course_id 2:
<img width="276" alt="screen shot 2017-07-28 at 11 30 56 am" src="https://user-images.githubusercontent.com/7613936/28731420-b2703fc2-7388-11e7-87fd-185137caeb91.png">

And course 2 has user_id 11 (me) as the instructor:
<img width="256" alt="screen shot 2017-07-28 at 11 31 06 am" src="https://user-images.githubusercontent.com/7613936/28731438-c252f13c-7388-11e7-93ac-82248e4c0460.png">

Here's the error file:
```(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'DashboardDataAnalyzer' object has no attribute 'problem_metrics'"
p3
sS'layer'
p4
S'/home/ubuntu/workspace/python-server/web2py/applications/runestone/controllers/dashboard.py'
p5
sS'code'
p6
S'from os import path\nimport os\nimport logging\nfrom datetime import date, timedelta, datetime\nfrom operator import itemgetter\nfrom paver.easy import sh\n\nlogger = logging.getLogger("web2py.root")\nlogger.setLevel(logging.DEBUG)\n\n\n# this is for admin links\n# use auth.requires_membership(\'manager\')\n#\n# create a simple index to provide a page of links\n# - re build the book\n# - list assignments\n# - find assignments for a student\n# - show totals for all students\n\n# select acid, sid from code as T where timestamp = (select max(timestamp) from code where sid=T.sid and acid=T.acid);\n\n@auth.requires_login()\ndef index():\n    selected_chapter = None\n    questions = []\n    sections = []\n\n    course = db(db.courses.id == auth.user.course_id).select().first()\n    assignments = db(db.assignments.course == course.id).select(db.assignments.ALL, orderby=db.assignments.name)\n    logger.debug("getting chapters for {}".format(auth.user.course_name))\n    chapters = db(db.chapters.course_id == auth.user.course_name).select()\n    for chapter in chapters.find(lambda chapter: chapter.chapter_label==request.get_vars[\'chapter\']):\n        selected_chapter = chapter\n    if selected_chapter is None:\n        selected_chapter = chapters.first()\n\n    logger.debug("making an analyzer")\n    data_analyzer = DashboardDataAnalyzer(auth.user.course_id)\n    logger.debug("loading chapter metrics for course {}".format(auth.user.course_name))\n    data_analyzer.load_chapter_metrics(selected_chapter)\n    logger.debug("loading problem metrics")\n    problem_metrics = data_analyzer.problem_metrics\n    logger.debug("loading progress_metrics metrics")\n    progress_metrics = data_analyzer.progress_metrics\n\n    logger.debug("starting problem_id, metric loop")\n    for problem_id, metric in problem_metrics.problems.iteritems():\n        stats = metric.user_response_stats()\n\n        if data_analyzer.questions[problem_id]:\n            entry = {\n                "id": problem_id,\n                "text": metric.problem_text,\n                "chapter": data_analyzer.questions[problem_id].chapter,\n                "sub_chapter": data_analyzer.questions[problem_id].subchapter,\n                "correct": stats[2],\n                "correct_mult_attempt": stats[3],\n                "incomplete": stats[1],\n                "not_attempted": stats[0],\n                "attemptedBy": stats[1] + stats[2] + stats[3]\n                }\n        else:\n            entry = {\n                "id": problem_id,\n                "text": metric.problem_text,\n                "correct": stats[2],\n                "correct_mult_attempt": stats[3],\n                "incomplete": stats[1],\n                "not_attempted": stats[0],\n                "attemptedBy": stats[1] + stats[2] + stats[3]\n                }\n        questions.append(entry)\n\n    logger.debug("getting questsions")\n    questions = sorted(questions, key=itemgetter("id"))\n    logger.debug("starting sub_chapter loop")\n    for sub_chapter, metric in progress_metrics.sub_chapters.iteritems():\n        sections.append({\n            "id": metric.sub_chapter_label,\n            "text": metric.sub_chapter_text,\n            "readPercent": metric.get_completed_percent(),\n            "startedPercent": metric.get_started_percent(),\n            "unreadPercent": metric.get_not_started_percent()\n            })\n\n    read_data = []\n    recent_data = []\n    logger.debug("getting user activity")\n    user_activity = data_analyzer.user_activity\n\n    for user, activity in user_activity.user_activities.iteritems():\n        read_data.append({\n            "student":activity.name,  # causes username instead of full name to show in the report, but it works  ?? how to display the name but use the username on click??\n            "sid":activity.username,\n            "count":activity.get_page_views()\n            })\n\n        recent_data.append({\n            "student":activity.name,\n            "sid":activity.username,\n            "count":activity.get_recent_page_views()\n            })\n\n    logger.debug("finishing")\n    studentactivity = [{\n    "data":read_data,\n    "name":"Sections Read"\n    },{\n    "data":read_data,\n    "name":"Exercises Correct"\n    },{\n    "data":read_data,\n    "name":"Exercises Missed"\n    }]\n\n    recentactivity = [{\n    "data":recent_data,\n    "name":"Sections Read"\n    },{\n    "data":recent_data,\n    "name":"Exercises Correct"\n    },{\n    "data":recent_data,\n    "name":"Exercises Missed"\n    }]\n\n    return dict(assignments=assignments, course_name=auth.user.course_name, course_id=auth.user.course_name, questions=questions, sections=sections, chapters=chapters, selected_chapter=selected_chapter, studentactivity=studentactivity, recentactivity=recentactivity)\n\n@auth.requires_login()\ndef studentreport():\n    data_analyzer = DashboardDataAnalyzer(auth.user.course_id)\n    data_analyzer.load_user_metrics(request.get_vars["id"])\n    data_analyzer.load_assignment_metrics(request.get_vars["id"])\n\n    chapters = []\n    for chapter_label, chapter in data_analyzer.chapter_progress.chapters.iteritems():\n        chapters.append({\n            "label": chapter.chapter_label,\n            "status": chapter.status_text(),\n            "subchapters": chapter.get_sub_chapter_progress()\n            })\n    activity = data_analyzer.formatted_activity.activities\n\n\n    return dict(course_id=auth.user.course_id, course_name=auth.user.course_name, user=data_analyzer.user, chapters=chapters, activity=activity, assignments=data_analyzer.grades)\n\ndef studentprogress():\n    return dict(course_name=auth.user.course_name)\n\ndef grades():\n    row = db(db.courses.id == auth.user.course_id).select(db.courses.course_name, db.courses.base_course).first()\n    course = db(db.courses.id == auth.user.course_id).select().first()\n    assignments = db(db.assignments.course == course.id).select(db.assignments.ALL, orderby=(db.assignments.duedate, db.assignments.id))\n    students = db(\n        (db.user_courses.course_id == auth.user.course_id) &\n        (db.auth_user.id == db.user_courses.user_id)\n    ).select(db.auth_user.username, db.auth_user.first_name,db.auth_user.last_name,db.auth_user.id, orderby=(db.auth_user.last_name, db.auth_user.first_name))\n    query = "select score, points, assignments.id, auth_user.id from auth_user join grades on (auth_user.id = grades.auth_user) join assignments on (grades.assignment = assignments.id) where points is not null and assignments.course = \'%s\' and auth_user.id in (select user_id from user_courses where course_id = \'%s\') order by last_name, first_name, assignments.duedate, assignments.id;"\n    rows = db.executesql(query, [course[\'id\'], course[\'id\']])\n\n    gradetable = []\n    averagerow = []\n\n    #now use the query result to form the rows in the table\n    currentrow=0\n    for student in students:\n        studentrow = []\n        studentrow.append(student.first_name + " " + student.last_name)\n        for assignment in assignments:\n            try:\n                if rows[currentrow][2] == assignment[\'id\'] and rows[currentrow][3] == student.id and rows[currentrow][1] != None:\n                        studentrow.append(100 * rows[currentrow][0]/rows[currentrow][1])\n                        currentrow += 1\n                else:\n                    studentrow.append(\'n/a\')\n\n            except:  #This exception should only trigger when the bottom right slot in the table has a grade of \'n/a\'\n                studentrow.append(\'n/a\')\n        gradetable.append(studentrow)\n\n    #Then build the average row for the table\n\n    for col in range(1, len(assignments)+1):\n        applicable = False\n        averagedivide = len(students)\n        average = 0\n        for grade in range(len(students)):\n            if gradetable[grade][col] != \'n/a\':\n                average += gradetable[grade][col]\n                gradetable[grade][col] = str(round(gradetable[grade][col], 2))\n                applicable = True\n            else:\n                averagedivide = averagedivide - 1\n        if applicable:\n            averagerow.append(str(round(average/averagedivide, 2)))\n        else:\n            averagerow.append(\'n/a\')\n\n    return dict(course_id=auth.user.course_name, course_name=auth.user.course_name, assignments=assignments, students=students, gradetable=gradetable, averagerow=averagerow)\n\ndef questiongrades():\n    course = db(db.courses.id == auth.user.course_id).select().first()\n    assignment = db(db.assignments.id == request.vars.assignment_id)(db.assignments.course == course.id).select().first()\n    sid = request.vars.sid\n    student = db(db.auth_user.username == sid).select(db.auth_user.first_name, db.auth_user.last_name)\n\n    query = ("select questions.name, score, points from questions join assignment_questions on (questions.id = assignment_questions.question_id) join question_grades on (questions.name = question_grades.div_id) where assignment_id = \'%s\' and sid = %s;")\n    rows = db.executesql(query, [assignment[\'id\'], sid])\n\n    return dict(course_id=auth.user.course_id, course_name=auth.user.course_name, assignment=assignment, student=student, rows=rows, total=0)\n\ndef exercisemetrics():\n    data_analyzer = DashboardDataAnalyzer(auth.user.course_id)\n    data_analyzer.load_exercise_metrics(request.get_vars["id"])\n    problem_metrics = data_analyzer.problem_metrics\n\n    prob_id = request.get_vars["id"]\n    answers = []\n    attempt_histogram = []\n\n    problem_metric = problem_metrics.problems[prob_id]\n    response_frequency = problem_metric.aggregate_responses\n\n    for username, user_responses in problem_metric.user_responses.iteritems():\n        responses = user_responses.responses[:4]\n        responses += [\'\'] * (4 - len(responses))\n        answers.append({\n            "user":user_responses.user,\n            "username": user_responses.username,\n            "answers":responses\n            })\n\n    for attempts, count in problem_metric.user_number_responses().iteritems():\n        attempt_histogram.append({\n            "attempts": attempts,\n            "frequency": count\n            })\n\n    return dict(course_name=auth.user.course_name, answers=answers, response_frequency=response_frequency, attempt_histogram=attempt_histogram, exercise_label=problem_metric.problem_text)\n\nresponse._vars=response._caller(index)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/ubuntu/workspace/python-server/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/ubuntu/workspace/python-server/web2py/applications/runestone/controllers/dashboard.py", line 242, in <module>\n  File "/home/ubuntu/workspace/python-server/web2py/gluon/globals.py", line 417, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/ubuntu/workspace/python-server/web2py/gluon/tools.py", line 4241, in f\n    return action(*a, **b)\n  File "/home/ubuntu/workspace/python-server/web2py/applications/runestone/controllers/dashboard.py", line 43, in index\n    problem_metrics = data_analyzer.problem_metrics\nAttributeError: \'DashboardDataAnalyzer\' object has no attribute \'problem_metrics\'\n'
p11
s.
```

Regarding the bigger next/previous buttons, my hack doesn't look right on mouse over, and the animation when you scroll to the bottom of the page recently broke it as well, so it's not PR-ready as it is, and since we're wrapping up our summer session, it's unlikely I'll end up with the chance to polish it.

We do have hypothes.is running, and it wasn't too hard to do so. In `/thinkcspy/_sources/_templates/plugin_layouts/sphinx_bootstrap/layout.html` I added:

```
<script type="text/javascript" >
  {
    var resizerTimeout = null; 
    var initialTimerInterval = setInterval(function(){
      if (window.annotator){ 
        clearInterval(initialTimerInterval);
        setInterval(resizeBook, 1000);
      }
    },300);


    function resizeBook() {
      setTimeout(function() {
        var sidebarWidth = $(".annotator-toolbar").width(); 
        if (window.annotator.isOpen()) {
          sidebarWidth += $(".annotator-outer").width();
        }

        var windowWidth = $(window).width();
        var bookWidth = windowWidth - sidebarWidth;

        $(".navbar-default, .footer").css({width:bookWidth}); 
        $("#relations-next").css({"right":sidebarWidth+"px"});  
        // $(".container").css({"max-width": "none !important;"});

        var currentMarginRight = parseInt($("#main-content").css("margin-right")); 
        if (window.annotator.isOpen() && (currentMarginRight < sidebarWidth+10)) {
          $("#main-content").css({"margin-right":sidebarWidth+"px"}); 
        } else {
          $("#main-content").css({"margin-right":""}); 
        }
      }, 100);
    }
  }
</script>
<script async src="https://hypothes.is/embed.js"></script>
```

The JS moves the body of the textbook to the left when the hyothes.is sidebar is open. It's a little jerky right now, but might serve as a helpful starting point.

Please let me know if you have any other questions about our approach, I'll be sure to make time to answer them. 🙂

**Comment by bnmnetp** [comment]
OK, I think I may know what is going on.  When you did a `runestone build` of thinkcspy you have to have your DBHOST, DBUSER, DBPASS, and DBNAME environment variables set to point at your postgresql database, so that it builds some tables in the database that support this dashboard.  I'm guessing that if you were to look in the database at the chapters table you would not find any rows for the thinkcspy course, probably that table is empty.

That is the only explanation that makes any sense to me.

Brad

**Comment by MarkEstefanos** [comment]
The chapters table is indeed empty. I get this at the end of `runestone build`:

```
trying alternative database access due to  No module named serializers
```
I got the same error with pydal and gluon before pip installing them. `pip install serializers`  gives me:
```
Could not find a version that satisfies the requirement serializers (from versions: )
No matching distribution found for serializers.
```

That being said, the rest of the database tables got there somehow?

**Comment by bnmnetp** [comment]
When you do `runestone build` it actually uses sqlalchemy, so there is no reason to install pydal or gluon or serializers.  Those messages come up because when you are in the instructors interface and build your custom course, then the build happens from "inside" web2py and uses its ORM (DAL) to update the database.

Do you also see a bunch of messages like:
```
Unable to save to source_code table in activecode.py. Possible problems:
  1. dburl or course_id are not set in conf.py for your book
  2. unable to connect to the database using dburl
```

So, if you set those environment variables and rebuild your thinkcspy with the environment set up correctly you should see that those chapters are populated.  You will know that they are being populated because the build will tell you that it is populating the table for each chapter at the very end of the build.

**Comment by bnmnetp** [comment]
The rest of the tables are populated from the models folder.  Whenever you access any dynamic page in web2py it loads all of the models and creates new tables if necessary.

**Comment by MarkEstefanos** [comment]
I'm getting neither of those errors, nor do I see a place to put course_id or dburl in conf.py

Here's my entire console output:
```
$ runestone build
Building with Runestone 2.7.14
---> runestone.build
git describe --long
('Building into ', './build/thinkcspy')
mkdir_p path('././build/thinkcspy')
mkdir_p path('./build/thinkcspy')
mkdir_p path('./build/thinkcspy/doctrees')
sphinx-build  -b html -d ./build/thinkcspy/doctrees -c . -Abasecourse=thinkcspy -Arunestone_version=2.7.14 -Acourse_id=thinkcspy -Apython3=true -Adburl=postgresql://[removed] -Abuild_info=3.7.2 -Aappname=runestone -Aloglevel=10 -Alogin_required=false -Acourse_url=https://summer-python.minerva.kgi.edu -Ause_services=true ././_sources/ ./build/thinkcspy
Running Sphinx v1.4.5
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
no targets are out of date.
build succeeded.
trying alternative database access due to  No module named serializers
Creating Chapter Information for ./_sources/index.rst
Done, thinkcspy build successful
```
